### DISCUSSION TITLE
Japanese_SOFA_model_Test2_Plus

### DISCUSSION THREAD

**Discussion by Greenleaf2001** [qiuqiao/SOFA#42] [Pretrained Model Sharing]
### **DOWNLOAD [HERE](https://github.com/Greenleaf2001/SOFA_Models/releases/tag/JPN_Test2_Plus)**
- Release Date: Mar. 22, 2025
- Code version: v1.0.3
- Model version: Test2_Plus
- Languages used: Japanese
- Dictionaty used: Japanese-extention (Romaji prefered) (Please use phonemes supported by hparams.yaml）
- Applicability: Singing Voice
- Training Data: See data_providers.md
- Hyperparameters:See hparams.yaml

---

- 发布日期：2025.3.22
- 代码版本：v1.0.3
- 模型版本：Test2_Plus
- 使用语言：日语
- 使用词典：Japanese-extention（推荐使用Romaji）（请以hparams.yaml支持的音素为准）
- 适用范围：歌声
- 训练数据：参见data_providers.md
- 超参数：参见hparams.yaml

**Comment by Greenleaf2001** [comment]
Compared to #22 
The original annotations have been reviewed and optimized to ensure a more stable and consistent annotation style.

In terms of model performance, there appears to be some improvement in the boundary delineation between consonants and vowels, though the enhancement may be relatively modest.

**Comment by Greenleaf2001** [comment]
Compared to Test2
Thanks to @wolfgitpr for config providing. The size of the model has been significantly reduced.

Details：

```
model:
  hidden_dims: 128
  down_sampling_factor: 3
  down_sampling_times: 5
  channels_scaleup_factor: 1.3
```
```
optimizer_config:
  total_steps: 100000
  weight_decay: 0.1
  lr:
    backbone: 0.001
    head: 0.001
  freeze:
    backbone: False
    head: False
```
```
loss_config:
  losses:
    weights: [8.0, 0.1, 0.01, 0.1, 2.0, 1.0, 3.0]
    enable_RampUpScheduler: [False,False,False,True,True,True,True]
  function:
    num_bins: 10
    alpha: 0.999
    label_smoothing: 0.08
    pseudo_label_ratio: 0.3
```
```
gradient_clip_val: 0.5
```
    
The rest remains unchanged.
